[features]
seeds = false
skip-lint = false
[programs.devnet]
self_intro = "7aKYn6hz2W43aGx4kXXwEihLdYbnwM5qzvDPft5iHAfk"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/home/priks/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
